### ISSUE TITLE
Handle single band rasters in smoosh

### ISSUE THREAD

**Issue by dnomadb** [mapbox/grib-doctor#10]
While it is counterintuitive in some ways, this will enable better program flow.

singleband `.grib` in --> singleband `.tif` out.

cc @ian29

**Comment by ian29** [comment]
THANKS DAMON

**Comment by dnomadb** [comment]
Implemented in https://github.com/mapbox/grib-doctor/commit/62d181d208ae650c7149c7dbf9e299131f376707
